export const BLOCKED_COUNTRIES = {
    AF: 'Afghanistan',
    CU: 'Cuba',
    KP: 'Democratic People\'s Republic of Korea',
    IR: 'Iran',
    IQ: 'Iraq',
    CN: 'People’s Republic of China',
    RU: 'Russian Federation',
    SO: 'Somalia',
    SD: 'Sudan',
    SY: 'Syria',
    AE: 'United Arab Emirates',
    US: 'United States of America',
    VU: 'Venezuela',
    YE: 'Yemen',
}
